// Client-side export helpers (spec §19): CSV, JSON and printable HTML/PDF.

function download(filename: string, content: string, mime: string) {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportJSON(filename: string, data: unknown) {
  download(`${filename}.json`, JSON.stringify(data, null, 2), "application/json");
}

export function exportCSV(filename: string, rows: Record<string, unknown>[]) {
  if (rows.length === 0) {
    download(`${filename}.csv`, "", "text/csv");
    return;
  }
  const headers = Object.keys(rows[0]);
  const escape = (v: unknown) => {
    const s = v == null ? "" : Array.isArray(v) ? v.join("; ") : String(v);
    return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
  };
  const lines = [
    headers.join(","),
    ...rows.map((r) => headers.map((h) => escape(r[h])).join(",")),
  ];
  download(`${filename}.csv`, lines.join("\n"), "text/csv");
}

/** Opens a printable report window (use the browser's "Save as PDF"). */
export function printReport(title: string, bodyHtml: string) {
  const win = window.open("", "_blank", "width=900,height=700");
  if (!win) return;
  win.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${title}</title>
  <style>
    body{font-family:Inter,system-ui,sans-serif;color:#16223a;margin:40px;line-height:1.5}
    h1{font-size:20px;margin:0 0 4px} h2{font-size:14px;margin:24px 0 8px;color:#1b3a6b;border-bottom:1px solid #e2e8f0;padding-bottom:4px}
    .meta{color:#64748b;font-size:12px;margin-bottom:16px}
    table{width:100%;border-collapse:collapse;font-size:12px;margin:8px 0}
    th,td{border:1px solid #e2e8f0;padding:6px 8px;text-align:left}
    th{background:#f1f5f9}
    .disclaimer{margin-top:24px;font-size:11px;color:#64748b;border-top:1px solid #e2e8f0;padding-top:12px}
  </style></head><body>${bodyHtml}
  <p class="disclaimer">Generated by Governance Studio (demo). This report supports governance work but does not
  guarantee legal or regulatory compliance. Indicators are reported separately. Regulatory classifications are
  assumptions requiring qualified legal review.</p>
  </body></html>`);
  win.document.close();
  win.focus();
  setTimeout(() => win.print(), 300);
}
